//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

pub use super::booking::Entity as Booking;
pub use super::permission::Entity as Permission;
pub use super::room::Entity as Room;
pub use super::room_booking::Entity as RoomBooking;
pub use super::roomphotos::Entity as Roomphotos;
pub use super::user::Entity as User;
pub use super::user_permission::Entity as UserPermission;
