name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile
            context: .
          - name: frontend
            dockerfile: Dockerfile.frontend
            context: ./frontend
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image - ${{ matrix.name }}
        run: |
          docker build \
            --file ${{ matrix.dockerfile }} \
            --tag ${{ matrix.name }}:$(date +%s) \
            ${{ matrix.context }