name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: Dockerfile
            push: true
            context: .
          - name: frontend
            dockerfile: frontend/Dockerfile
            push: true
            context: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT}}
      - name: Build Docker Image - ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ matrix.dockerfile }}
          context: ${{ matrix.context }}
          tags: jisef/${{ matrix.name }}:latest
        # run: "docker build --file ${{ matrix.dockerfile }} --tag ${{ matrix.name }}:$(date +%s) ${{ matrix.context }}"